displayName=AutoInfoUploadConfig
author=Yarth
description=Plugin uploads session data every x minutes to external site for bingo tracking.
tags=bingo
version=0.1
plugins=com.bingo_auto_info_upload.BingoAutoInfoUploadPlugin
build=standard